insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 66, 67);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 70, 97);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 47, 93);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 35, 72);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 29, 76);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 74, 85);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 9, 96);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 97, 90);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 86, 50);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 2, 94);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 60, 82);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 68, 66);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 56, 33);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 30, 68);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 29, 54);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 79, 37);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 82, 46);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 32, 22);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 60, 18);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 71, 90);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 58, 25);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 89, 72);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 46, 95);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 15, 66);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 14, 50);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 77, 49);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 50, 100);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 17, 78);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 18, 48);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 46, 48);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 36, 45);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 74, 7);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 4, 90);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 49, 40);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 7, 84);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 29, 61);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 4, 62);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 86, 97);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 82, 17);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 74, 87);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 75, 97);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 74, 22);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 66, 31);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '타인을 욕설 및 비방, 명예훼손하였습니다.', sysdate, '욕설/비방', 22, 86);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 35, 81);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 60, 95);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 92, 71);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트의 타이틀과 프로젝트의 내용이 다릅니다.', sysdate, '프로젝트 연관성', 40, 5);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 72, 78);
insert into tblWarning(warningSeq,content,regDate,warnCategory,sMemberSeq,rMemberSeq) values(warningSeq.nextVal, '프로젝트에 기재된 내용이 허위성 광고인거 같습니다.', sysdate, '허위사실유포', 5, 16);

commit;
select * from tblWarning
